<?php
/**
 * @file
 * Love INC Brevard Custom Module
 * @author civicrm_lead
 */

 /**
 * Allow modules to modify a webform component that is going to be rendered in a form.
 *
 * @param array $element
 *   The display element as returned by _webform_render_component().
 * @param array $component
 *   A Webform component array.
 *
 * @see _webform_render_component()
 */

function loveincbrevard_webform_component_render_alter(&$element, &$component) {
  if (strcmp($element['#webform_component']['form_key'], 'civicrm_1_activity_1_cg10_custom_47') == 0) {
		$element['#attached']['js'][] = array(
		  'type' => 'inline',
		  'data' => '(function ($) { ' . 
		  '$(document).ready( function(){var validator = $("#webform-client-form-2").validate({}); $("#edit-submitted-civicrm-1-activity-1-cg10-custom-47").rules("add", {min:1 ,messages: {min:"Activity End Date Time is earlier than Activity Start Date Time.  Please correct before submitting."}});} ); ' .
		  '$(window).load( function(){set_time_completed_in_minutes();} ); ' .
		  '$(".month.form-select").change(function(){set_time_completed_in_minutes();}); ' . 
		  '$(".day.form-select").change(function(){set_time_completed_in_minutes();}); ' . 
		  '$(".year.form-select").change(function(){set_time_completed_in_minutes();}); ' . 
		  '$(".hour.form-select").change(function(){set_time_completed_in_minutes();}); ' . 
		  '$(".minute.form-select").change(function(){set_time_completed_in_minutes();}); ' . 
		  '$(".form-item-submitted-civicrm-1-activity-1-activity-activity-date-time-timepart-ampm").change(function(){set_time_completed_in_minutes($(this));}); ' . 
		  '$(".form-item-submitted-activity-end-time-ampm").change(function(){set_time_completed_in_minutes($(this));}); ' . 
		  //'$("#webform-client-form-2").validate(); ' .
		  //'$("#edit-submitted-civicrm-1-activity-1-cg10-custom-47").rules("add", {min:1 ,messages: {min:"Activity End Date Time is earlier than Activity Start Date Time.  Please correct before submitting."}}); ' .
			//'$( "#webform-client-form-2" ).validate({rules: {"#edit-submitted-civicrm-1-activity-1-cg10-custom-47": {required: true,min: 1}}});' .
		  ' function set_time_completed_in_minutes() { ' .
		  		' var startDateTimeYear =  $("#edit-submitted-civicrm-1-activity-1-activity-activity-date-time-year").val();' .
		  		' var startDateTimeMonth = $("#edit-submitted-civicrm-1-activity-1-activity-activity-date-time-month").val();' .
		  		' var startDateTimeDay = $("#edit-submitted-civicrm-1-activity-1-activity-activity-date-time-day").val();' .
		  		' var startDateTimeHour = $("#edit-submitted-civicrm-1-activity-1-activity-activity-date-time-timepart-hour").val();' .
		  		' var startDateTimeMinute = $("#edit-submitted-civicrm-1-activity-1-activity-activity-date-time-timepart-minute").val();' .
				  ' if($("#edit-submitted-civicrm-1-activity-1-activity-activity-date-time-timepart-ampm-am").is(":checked")) { ' .
				  ' if (parseInt(startDateTimeHour) == 12) startDateTimeHour = 0;' .
				  ' } else { if (parseInt(startDateTimeHour) < 12) startDateTimeHour = parseInt(startDateTimeHour) + 12;}' .
				  ' var startDateTime = new Date(startDateTimeYear,startDateTimeMonth,startDateTimeDay,startDateTimeHour,startDateTimeMinute); ' .
				  ' ' .
		  		' var endDateTimeYear =  $("#edit-submitted-activity-end-date-year").val();' .
		  		' var endDateTimeMonth = $("#edit-submitted-activity-end-date-month").val();' .
		  		' var endDateTimeDay = $("#edit-submitted-activity-end-date-day").val();' .
		  		' var endDateTimeHour = $("#edit-submitted-activity-end-time-hour").val();' .
		  		' var endDateTimeMinute = $("#edit-submitted-activity-end-time-minute").val();' .
				  ' if($("#edit-submitted-activity-end-time-ampm-am").is(":checked")) { ' .
				  ' if (parseInt(endDateTimeHour) == 12) endDateTimeHour = 0;' .
				  ' } else { if (parseInt(endDateTimeHour) < 12) endDateTimeHour = parseInt(endDateTimeHour) + 12;}' .
				  ' var endDateTime = new Date(endDateTimeYear,endDateTimeMonth,endDateTimeDay,endDateTimeHour,endDateTimeMinute); ' .
				  ' totalMinutes = (endDateTime.getTime() - startDateTime.getTime()) / 60000; '. 
				  ' $("#edit-submitted-civicrm-1-activity-1-cg10-custom-47").val(totalMinutes);' .
				  ' $("#edit-submitted-total-time").val((Math.floor(totalMinutes / 60) + " hours " + Math.floor(totalMinutes % 60) + " mins."));' .
				  ' if (totalMinutes < 0) alert("Activity End Date Time is earlier than Activity Start Date Time.  Please correct before submitting.");' .
		  ' }' .
			'}(jQuery));',
 		  'scope' => 'footer',
		  'group' => JS_THEME,
		  'weight' => 5,
		);
  }
}
 
 /*
  * 
  * NOT CURRENTLY USED
  *
  * */
  
/**
 * Implements hook_webform_submission_presave().
 * Uses cached instance of wf_crm_webform_postprocess that was created during validation.
 */
function loveincbrevard_webform_submission_presave($node, &$submission) {
  if (!empty($node->webform_civicrm)) {
  	set_time_completed_in_minutes($node, $submission);
  }
}

/**
 * helper function set_time_completed_in_minutes()
 */
function set_time_completed_in_minutes($node, &$submission) {
	 	$activity_start_date_str = '';
	 	$activity_start_time_str = '';
	 	$activity_end_date_str = '';
	 	$activity_end_time_str = '';
	 	$time_completed_in_minutes_key = -1;
		foreach ($node->webform['components'] as $key => $component) {
		  if (isset($submission->data[$key][0])) {
				if (!strcmp($component['form_key'], 'civicrm_1_activity_1_activity_activity_date_time')) {
					$activity_start_date_str = $submission->data[$key][0];
				} else if (!strcmp($component['form_key'],'civicrm_1_activity_1_activity_activity_date_time_timepart')) {
					$activity_start_time_str = $submission->data[$key][0];
				} else if (!strcmp($component['form_key'],'activity_end_date')) {
					$activity_end_date_str = $submission->data[$key][0];
				} else if (!strcmp($component['form_key'],'activity_end_time')) {
					$activity_end_time_str = $submission->data[$key][0];
				} 
			}
			if (!strcmp($component['form_key'],'civicrm_1_activity_1_cg10_custom_47')) {
					$time_completed_in_minutes_key = $key;
			}
		}
		
		$activity_start_datetime =  strtotime($activity_start_date_str.' '.$activity_start_time_str);
		$activity_end_datetime =  strtotime($activity_end_date_str.' '.$activity_end_time_str);
		
		if ($activity_end_datetime > $activity_start_datetime && $time_completed_in_minutes_key > -1) {
			$submission->data[$time_completed_in_minutes_key][0] = ($activity_end_datetime - $activity_start_datetime) / 60; 
		} else {
			$submission->data[$time_completed_in_minutes_key][0] = 0;
		}
}
?>