<?php
/**
 * @file
 * Love INC Brevard Custom Module
 * @author civicrm_lead
 */

 /**
 * Allow modules to modify a webform component that is going to be rendered in a form.
 *
 * @param array $element
 *   The display element as returned by _webform_render_component().
 * @param array $component
 *   A Webform component array.
 *
 * @see _webform_render_component()
 */

function loveincbrevard_webform_component_render_alter(&$element, &$component) {
  if (strcmp($element['#webform_component']['form_key'], 'civicrm_1_activity_1_cg10_custom_47') == 0) {
		drupal_add_js(drupal_get_path('module', 'loveincbrevard').'/js/loveincbrevard.js', 'file');
  }
}
   
/**
 * Implements hook_webform_submission_presave().
 * Uses cached instance of wf_crm_webform_postprocess that was created during validation.
 */
function loveincbrevard_webform_submission_presave($node, &$submission) {
  if (!empty($node->webform_civicrm)) {
  	set_time_completed_in_minutes($node, $submission);
  }
}

/**
 * helper function set_time_completed_in_minutes()
 */
function set_time_completed_in_minutes($node, &$submission) {
	 	$activity_start_date_str = '';
	 	$activity_start_time_str = '';
	 	$activity_end_date_str = '';
	 	$activity_end_time_str = '';
	 	$time_completed_in_minutes_key = -1;
		foreach ($node->webform['components'] as $key => $component) {
		  if (isset($submission->data[$key][0])) {
				if (!strcmp($component['form_key'], 'civicrm_1_activity_1_activity_activity_date_time')) {
					$activity_start_date_str = $submission->data[$key][0];
				} else if (!strcmp($component['form_key'],'civicrm_1_activity_1_activity_activity_date_time_timepart')) {
					$activity_start_time_str = $submission->data[$key][0];
				} else if (!strcmp($component['form_key'],'activity_end_date')) {
					$activity_end_date_str = $submission->data[$key][0];
				} else if (!strcmp($component['form_key'],'activity_end_time')) {
					$activity_end_time_str = $submission->data[$key][0];
				} 
			}
			if (!strcmp($component['form_key'],'civicrm_1_activity_1_cg10_custom_47')) {
					$time_completed_in_minutes_key = $key;
			}
		}
		
		$activity_start_datetime =  strtotime($activity_start_date_str.' '.$activity_start_time_str);
		$activity_end_datetime =  strtotime($activity_end_date_str.' '.$activity_end_time_str);
		
		if ($activity_end_datetime > $activity_start_datetime && $time_completed_in_minutes_key > -1) {
			$submission->data[$time_completed_in_minutes_key][0] = ($activity_end_datetime - $activity_start_datetime) / 60; 
		} else {
			$submission->data[$time_completed_in_minutes_key][0] = 0;
		}
}
?>